---
- name: Install git
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - git

- name: Add system group
  group: name="{{ app_name }}"

- name: Add system user
  user: name="{{ app_name }}" group="{{ app_name }}" home="/home/{{ app_name }}"

- name: Ensure .ssh directory exists
  file: path="/home/{{ app_name }}/.ssh" state=directory mode=0700 owner="{{ app_name }}" group="{{ app_name }}"

- name: Copy aws deploy key
  action: copy src="{{ prestashop_deploy_key }}" dest="/home/{{ app_name }}/.ssh/{{ prefix }}" owner="{{ app_name }}" group="{{ app_name }}" mode=0600

- name: gitconfig template
  template: src=gitconfig.j2 dest="/home/{{ app_name }}/.gitconfig" owner="{{ app_name }}" group="{{ app_name }}"

- name: Set cache/class_index.php mutable
  command: "chattr -i {{ web_root }}/cache/class_index.php"
  become: yes

- name: Create installation folder (web_root)
  file: path="{{ web_root }}" owner="{{ app_name }}" group="{{ app_name }}" state=directory recurse=yes mode='u=rwX,g=rwX,o=rX'

- name: git checkout repository for site
  git: repo="{{ gitrepo }}"
       dest="{{ web_root }}"
       ssh_opts="-o StrictHostKeyChecking=no -vvvv"
       accept_hostkey=True
       force=true
       key_file="/home/{{ app_name }}/.ssh/{{ prefix }}"
  become: yes
  become_user: "{{ app_name }}"

- name: Create app config file
  template: src=settings.inc.php.j2 dest="{{ web_root }}/config/settings.inc.php" owner="{{ app_name }}" group="{{ app_name }}"

- name: Copy Link.php overrides for production only
  template: src=Link.php.j2 dest="{{ web_root }}/override/classes/Link.php" owner="{{ app_name }}" group="{{ app_name }}"
  when: mode == "prod"

- name: Copy post_receive.php as github post receive webhook
  template: src=post_receive.php.j2 dest="{{ web_root }}/post_receive.php" owner="{{ app_name }}" group="{{ app_name }}"
  when: mode == "dev"

- name: Copy Git.php script. Required for git-status.php and git-commit.php
  copy: src="Git.php" dest="{{ web_root }}/Git.php" owner="{{ system_user }}" group="{{ system_group }}" 

- name: Generate git-status.php for server-side git status check 
  template: src=git-status.php.j2 dest="{{ web_root }}/git-status.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev"

- name: Generate git-commit.php for server-side git commit of modified files
  template: src=git-commit.php.j2 dest="{{ web_root }}/git-commit.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev"

- name: Ensure cache(s) writable
  file: dest="{{ item }}" state=directory mode=0775 recurse=yes owner="{{ app_name }}" group="{{ app_name }}"
  with_items:
    - "{{ web_root }}/cache/cachefs"
    - "{{ web_root }}/cache/smarty/cache"

- name: Copy site robots.txt
  copy: src="robots.txt" dest="{{ web_root }}/robots.txt" owner="{{ app_name }}" group="{{ app_name }}"
  tags:
    - robotstxt

- name: Add Disallow / for dev sites
  lineinfile: "dest={{ web_root }}/robots.txt regexp='^Disallow: /$' line='Disallow: /' insertafter='^User-agent'"
  when: mode == "dev"
  tags:
    - robotstxt

- name: Set cache/class_index.php immutable
  command: "chattr +i {{ web_root }}/cache/class_index.php"
  become: yes
