---
- name: Install git
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - git

- name: Add system group
  group: name="{{ system_user }}"

- name: Add system user
  user: name="{{ system_user }}" group="{{ system_group }}" home="/home/{{ system_user }}"

- name: Ensure .ssh directory exists
  file: path="/home/{{ system_user }}/.ssh" state=directory mode=0700 owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev"

- name: Copy aws deploy key
  action: copy src="{{ prestashop_deploy_key }}" dest="/home/{{ system_user }}/.ssh/{{ prefix }}" owner="{{ system_user }}" group="{{ system_group }}" mode=0600
  when: mode == "dev"

- name: gitconfig template
  template: src=gitconfig.j2 dest="/home/{{ system_user }}/.gitconfig" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev"

- name: Set psconfigs directory
  set_fact:
    psconfigs: "/opt/efs/psconfigs"
  when: psconfigs is undefined

- name: Set cache/class_index.php mutable
  command: "chattr -i {{ web_root }}/cache/class_index.php"
  become: yes
  when: mode != "stage"

- name: Delete cache/class_index.php
  file: 
    path: "{{ web_root }}/cache/class_index.php"
    state: absent
  when: mode != "stage"

- name: Create installation folder (web_root)
  file: path="{{ web_root }}" owner="{{ system_user }}" group="{{ system_group }}" state=directory recurse=yes mode='u=rwX,g=rwX,o=rX'

- name: git checkout repository for site
  git: repo="{{ gitrepo }}"
       dest="{{ web_root }}"
       ssh_opts="-o StrictHostKeyChecking=no -vvvv"
       accept_hostkey=True
       force=true
       key_file="/home/{{ system_user }}/.ssh/{{ prefix }}"
  become: yes
  become_user: "{{ system_user }}"
  when: mode == "dev"

- name: Ensure ~/psconfigs directory exists
  file: path="{{ psconfigs }}" state=directory mode=0700 owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == 'stage'

- name: Create app config file (stage) [PS 1.6.x]
  template:
    src: settings.inc.php.j2
    dest: "{{ psconfigs }}/settings.inc-{{ item.key }}.php"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
  with_dict: "{{ db_hosts }}"
  when: db_hosts is defined and mode == "stage" and ps_version != '1.7'

- name: Create app config file (dev) [PS 1.6.x]
  template: src=settings.inc.php.j2 dest="{{ web_root }}/config/settings.inc.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev" and ps_version != '1.7'

- name: Create app config file (stage) [PS 1.7.x]
  template:
    src: parameters.php.j2
    dest: "{{ psconfigs }}/parameters-{{ item.key }}.php"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
  with_dict: "{{ db_hosts }}"
  when: db_hosts is defined and mode == "stage" and ps_version == '1.7'

- name: Create app config file (dev) [PS 1.7.x]
  template: src=parameters.php.j2 dest="{{ web_root }}/app/config/parameters.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev" and ps_version == '1.7'

- name: Copy Link.php overrides (stage / prod)
  copy: src=Link.php dest="{{ psconfigs }}/Link.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "stage"

- name: Copy Link.php overrides for production only
  copy: src=Link.php dest="{{ web_root }}/override/classes/Link.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "prod"

- name: Create aws-s3-cron script (stage)
  template:
    src: aws-s3-cron.sh.j2
    dest: "/home/{{ system_user }}/aws-s3-cron.sh"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: 0755
  when: db_hosts is defined and mode == "stage"

- name: Create aws-s3-cron cronjob
  cron:
    minute: "*/3"
    job: "pgrep aws > /dev/null || /home/{{ system_user }}/aws-s3-cron.sh > /dev/null"

- name: Copy post_receive.php as github post receive webhook
  template: src=post_receive.php.j2 dest="{{ web_root }}/post_receive.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev"

- name: Copy Git.php script. Required for git-status.php and git-commit.php
  copy: src="Git.php" dest="{{ web_root }}/Git.php" owner="{{ system_user }}" group="{{ system_group }}" 
  when: mode == "dev"

- name: Generate git-status.php for server-side git status check 
  template: src=git-status.php.j2 dest="{{ web_root }}/git-status.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev"

- name: Generate git-commit.php for server-side git commit of modified files
  template: src=git-commit.php.j2 dest="{{ web_root }}/git-commit.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev"

- name: Ensure cache(s) writable
  file: dest="{{ item }}" state=directory mode=0775 recurse=yes owner="{{ system_user }}" group="{{ system_group }}"
  with_items:
    - "{{ web_root }}/cache/cachefs"
    - "{{ web_root }}/cache/smarty/cache"
  when: mode == "dev"

- name: Copy site robots.txt (stage)
  copy: src="robots.txt" dest="{{ psconfigs }}/robots.txt" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "stage"

- name: Copy site robots.txt
  copy: src="robots.txt" dest="{{ web_root }}/robots.txt" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev"
  tags:
    - robotstxt

- name: Add Disallow / for dev sites
  lineinfile: "dest={{ web_root }}/robots.txt regexp='^Disallow: /$' line='Disallow: /' insertafter='^User-agent'"
  when: mode == "dev"
  tags:
    - robotstxt

- name: Regenerate cache/class_index.php
  local_action: command "curl --silent http://{{ site_public_url }} > /dev/null"
  when: mode == "dev"

- name: Set cache/class_index.php immutable
  command: "chattr +i {{ web_root }}/cache/class_index.php"
  become: yes
  when: mode == "prod"
